---
title: "Finding Help"
---
    
There are a large number of resources are available to help with almost all coding issues, whether they are specific to R or more general. The first strategy once you feel stuck is to use Google (or an alternative search engine) to using a well thought out search term. You can also look into the [Main R FAQ](https://cran.r-project.org/doc/FAQ/R-FAQ.html) page for answers to more language specific questions. Another strategy that should not be ignored is to ask your experienced colleagues, but remember not to become a pest.

# Online help forums
If you cannot find a pre-existing answer to your issue, you can create a question to ask online. In order to ask a question effectively, it helps to phrase the question clearly, and, if you’re trying to solve a problem, to include a small, self-contained, reproducible example of the problem that others can execute. You will often find that this process alone answers the question. For information on how to ask questions, see, e.g., the [R mailing list posting guide](https://www.r-project.org/posting-guide.html), and the [document](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) about how to create reproducible examples for R on Stack Overflow. Once you have a well formatted question there are a number of possible forums available see below:

- [Stack Overflow](https://stackoverflow.com/) 
  - A well organized and formatted site for help and discussions about programming (in any language). 
  - It has a huge community and a large number of answers with a good level of searchability
  - Members of the community can be somewhat harsh to novices, especially if they perceive a question to have an obvious answer. For this reason it pays to put a good level of effort into creating a well thought out question. 
    - This harshness to novices is being clamped down on and in general the community is becoming more friendly and welcoming
    
- [The Statistical Computing with R subreddit](https://www.reddit.com/r/rstats/)
  - A specialised subreddit interested in R
  - The community is very welcoming especially to novices. 
  - Due to its smaller, more novice focused, user base complex questions may take longer to be answered than on Stack Overflow
  - Searchability is not great

# R email lists
The R Project maintains a number of subscription-based [email lists](https://www.r-project.org/mail.html) for posing and answering questions about R, including the general [R-help](https://stat.ethz.ch/mailman/listinfo/r-help) email list, the [R-devel](https://stat.ethz.ch/mailman/listinfo/r-devel) list for R code development, and [R-package-devel](https://stat.ethz.ch/mailman/listinfo/r-package-devel) list for developers of CRAN packages.
